### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Matlawton** [Matlawton/table-tennis#1]
@kienstra
This issue was created for a friend to help me understand some functions within my blocks of code.

**Comment by kienstra** [comment]
Hi @Matlawton,
Thanks for opening this. 

What's the result of these steps?

1. `git branch`
2. # Should say `make-changes`. If not, do `git checkout make-changes`
3. `git add -p`
4. # Hit 'Y' for every change you want to stage
5. `git commit "Add a button to start the game"`
6. `git push origin make-changes`
